/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ArtistEntry {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type ArtistName = string;
export type ExternalBlob = Uint8Array;
export type LoginResult = {
    'ok' : { 'displayName' : string, 'role' : string }
  } |
  { 'err' : string };
export interface PlatformUserRecord {
  'displayName' : string,
  'role' : string,
  'banned' : boolean,
  'emailHash' : string,
  'registeredAt' : Time,
}
export type ReleaseType = { 'ep' : null } |
  { 'album' : null } |
  { 'single' : null };
export type SongGenre = { 'rap' : null } |
  { 'other' : null } |
  { 'gospel' : null } |
  { 'kuduro' : null };
export type SongId = string;
export interface SongMetadata {
  'title' : SongTitle,
  'likeCount' : bigint,
  'songId' : SongId,
  'year' : [] | [bigint],
  'coverBlobId' : [] | [ExternalBlob],
  'featuring' : [] | [string],
  'genre' : SongGenre,
  'blobId' : ExternalBlob,
  'uploader' : Principal,
  'artist' : ArtistName,
  'producer' : [] | [string],
  'releaseType' : ReleaseType,
  'uploadedAt' : Time,
}
export type SongTitle = string;
export type Time = bigint;
export type Uploader = Principal;
export interface UserProfile {
  'bio' : [] | [string],
  'displayName' : string,
  'socialLinks' : [] | [string],
  'coverBlobId' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminDeleteSong' : ActorMethod<[SongId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banPlatformUser' : ActorMethod<[string, boolean], undefined>,
  'deletePlatformUser' : ActorMethod<[string], undefined>,
  'deleteSong' : ActorMethod<[SongId], undefined>,
  'getAllPlatformUsers' : ActorMethod<[], Array<PlatformUserRecord>>,
  'getAllSongIds' : ActorMethod<[], Array<SongId>>,
  'getAllSongs' : ActorMethod<[], Array<SongMetadata>>,
  'getAllUserProfiles' : ActorMethod<[], Array<ArtistEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfileVisitCount' : ActorMethod<[Principal], bigint>,
  'getSongLikes' : ActorMethod<[SongId], Array<Uploader>>,
  'getSongMetadata' : ActorMethod<[SongId], [] | [SongMetadata]>,
  'getSongsByArtist' : ActorMethod<[string], Array<SongMetadata>>,
  'getSongsByGenre' : ActorMethod<[SongGenre], Array<SongMetadata>>,
  'getSongsByReleaseType' : ActorMethod<[ReleaseType], Array<SongMetadata>>,
  'getSongsLikedByUser' : ActorMethod<[], Array<SongId>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasUserLikedSong' : ActorMethod<[SongId], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPlatformUserBanned' : ActorMethod<[string], boolean>,
  'loginPlatformUser' : ActorMethod<[string, string], LoginResult>,
  'recordProfileVisit' : ActorMethod<[Principal], undefined>,
  'registerPlatformUser' : ActorMethod<[string, string, string], undefined>,
  'registerPlatformUserWithPassword' : ActorMethod<
    [string, string, string, string],
    { 'ok' : null } |
      { 'emailTaken' : null }
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchSongs' : ActorMethod<[string], Array<SongMetadata>>,
  'toggleSongLike' : ActorMethod<[SongId], boolean>,
  'updateProfile' : ActorMethod<
    [string, [] | [string], [] | [ExternalBlob], [] | [string]],
    undefined
  >,
  'uploadSong' : ActorMethod<
    [
      SongTitle,
      ArtistName,
      SongGenre,
      ReleaseType,
      SongId,
      ExternalBlob,
      [] | [ExternalBlob],
      [] | [string],
      [] | [string],
      [] | [bigint],
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];