/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SongId = IDL.Text;
export const SongTitle = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const SongGenre = IDL.Variant({
  'rap' : IDL.Null,
  'other' : IDL.Null,
  'gospel' : IDL.Null,
  'kuduro' : IDL.Null,
});
export const ArtistName = IDL.Text;
export const ReleaseType = IDL.Variant({
  'ep' : IDL.Null,
  'album' : IDL.Null,
  'single' : IDL.Null,
});
export const Time = IDL.Int;
export const SongMetadata = IDL.Record({
  'title' : SongTitle,
  'likeCount' : IDL.Nat,
  'songId' : SongId,
  'coverBlobId' : IDL.Opt(ExternalBlob),
  'genre' : SongGenre,
  'blobId' : ExternalBlob,
  'uploader' : IDL.Principal,
  'artist' : ArtistName,
  'releaseType' : ReleaseType,
  'uploadedAt' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'socialLinks' : IDL.Opt(IDL.Text),
  'coverBlobId' : IDL.Opt(ExternalBlob),
});
export const Uploader = IDL.Principal;

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSong' : IDL.Func([SongId], [], []),
  'getAllSongIds' : IDL.Func([], [IDL.Vec(SongId)], ['query']),
  'getAllSongs' : IDL.Func([], [IDL.Vec(SongMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSongLikes' : IDL.Func([SongId], [IDL.Vec(Uploader)], ['query']),
  'getSongMetadata' : IDL.Func([SongId], [IDL.Opt(SongMetadata)], ['query']),
  'getSongsByArtist' : IDL.Func([IDL.Text], [IDL.Vec(SongMetadata)], ['query']),
  'getSongsByGenre' : IDL.Func([SongGenre], [IDL.Vec(SongMetadata)], ['query']),
  'getSongsByReleaseType' : IDL.Func(
      [ReleaseType],
      [IDL.Vec(SongMetadata)],
      ['query'],
    ),
  'getSongsLikedByUser' : IDL.Func([], [IDL.Vec(SongId)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserLikedSong' : IDL.Func([SongId], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongMetadata)], ['query']),
  'toggleSongLike' : IDL.Func([SongId], [IDL.Bool], []),
  'updateProfile' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'uploadSong' : IDL.Func(
      [
        SongTitle,
        ArtistName,
        SongGenre,
        ReleaseType,
        SongId,
        ExternalBlob,
        IDL.Opt(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SongId = IDL.Text;
  const SongTitle = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const SongGenre = IDL.Variant({
    'rap' : IDL.Null,
    'other' : IDL.Null,
    'gospel' : IDL.Null,
    'kuduro' : IDL.Null,
  });
  const ArtistName = IDL.Text;
  const ReleaseType = IDL.Variant({
    'ep' : IDL.Null,
    'album' : IDL.Null,
    'single' : IDL.Null,
  });
  const Time = IDL.Int;
  const SongMetadata = IDL.Record({
    'title' : SongTitle,
    'likeCount' : IDL.Nat,
    'songId' : SongId,
    'coverBlobId' : IDL.Opt(ExternalBlob),
    'genre' : SongGenre,
    'blobId' : ExternalBlob,
    'uploader' : IDL.Principal,
    'artist' : ArtistName,
    'releaseType' : ReleaseType,
    'uploadedAt' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'socialLinks' : IDL.Opt(IDL.Text),
    'coverBlobId' : IDL.Opt(ExternalBlob),
  });
  const Uploader = IDL.Principal;
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSong' : IDL.Func([SongId], [], []),
    'getAllSongIds' : IDL.Func([], [IDL.Vec(SongId)], ['query']),
    'getAllSongs' : IDL.Func([], [IDL.Vec(SongMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSongLikes' : IDL.Func([SongId], [IDL.Vec(Uploader)], ['query']),
    'getSongMetadata' : IDL.Func([SongId], [IDL.Opt(SongMetadata)], ['query']),
    'getSongsByArtist' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SongMetadata)],
        ['query'],
      ),
    'getSongsByGenre' : IDL.Func(
        [SongGenre],
        [IDL.Vec(SongMetadata)],
        ['query'],
      ),
    'getSongsByReleaseType' : IDL.Func(
        [ReleaseType],
        [IDL.Vec(SongMetadata)],
        ['query'],
      ),
    'getSongsLikedByUser' : IDL.Func([], [IDL.Vec(SongId)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserLikedSong' : IDL.Func([SongId], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchSongs' : IDL.Func([IDL.Text], [IDL.Vec(SongMetadata)], ['query']),
    'toggleSongLike' : IDL.Func([SongId], [IDL.Bool], []),
    'updateProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(ExternalBlob), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'uploadSong' : IDL.Func(
        [
          SongTitle,
          ArtistName,
          SongGenre,
          ReleaseType,
          SongId,
          ExternalBlob,
          IDL.Opt(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };