/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export type SongId = string;
export type Uploader = Principal;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type SongTitle = string;
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ArtistName = string;
export interface UserProfile {
    bio?: string;
    displayName: string;
    socialLinks?: string;
    coverBlobId?: ExternalBlob;
}
export interface SongMetadata {
    title: SongTitle;
    likeCount: bigint;
    songId: SongId;
    coverBlobId?: ExternalBlob;
    genre: SongGenre;
    blobId: ExternalBlob;
    uploader: Principal;
    artist: ArtistName;
    releaseType: ReleaseType;
    uploadedAt: Time;
    producer?: string;
    featuring?: string;
    year?: bigint;
}
export enum ReleaseType {
    ep = "ep",
    album = "album",
    single = "single"
}
export enum SongGenre {
    rap = "rap",
    other = "other",
    gospel = "gospel",
    kuduro = "kuduro"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteSong(songId: SongId): Promise<void>;
    getAllSongIds(): Promise<Array<SongId>>;
    getAllSongs(): Promise<Array<SongMetadata>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSongLikes(songId: SongId): Promise<Array<Uploader>>;
    getSongMetadata(songId: SongId): Promise<SongMetadata | null>;
    getSongsByArtist(artist: string): Promise<Array<SongMetadata>>;
    getSongsByGenre(genre: SongGenre): Promise<Array<SongMetadata>>;
    getSongsByReleaseType(releaseType: ReleaseType): Promise<Array<SongMetadata>>;
    getSongsLikedByUser(): Promise<Array<SongId>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasUserLikedSong(songId: SongId): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchSongs(searchTerm: string): Promise<Array<SongMetadata>>;
    toggleSongLike(songId: SongId): Promise<boolean>;
    updateProfile(displayName: string, bio: string | null, coverBlobId: ExternalBlob | null, socialLinks: string | null): Promise<void>;
    uploadSong(title: SongTitle, artist: ArtistName, genre: SongGenre, releaseType: ReleaseType, songId: SongId, audioBlob: ExternalBlob, coverBlobId: ExternalBlob | null, producer: string | null, featuring: string | null, year: bigint | null): Promise<void>;
}
import type { ArtistName as _ArtistName, ExternalBlob as _ExternalBlob, ReleaseType as _ReleaseType, SongGenre as _SongGenre, SongId as _SongId, SongMetadata as _SongMetadata, SongTitle as _SongTitle, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteSong(arg0: SongId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSong(arg0);
            return result;
        }
    }
    async getAllSongIds(): Promise<Array<SongId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongIds();
            return result;
        }
    }
    async getAllSongs(): Promise<Array<SongMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSongs();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSongs();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongLikes(arg0: SongId): Promise<Array<Uploader>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongLikes(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongLikes(arg0);
            return result;
        }
    }
    async getSongMetadata(arg0: SongId): Promise<SongMetadata | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongMetadata(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongMetadata(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByArtist(arg0: string): Promise<Array<SongMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByArtist(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByArtist(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByGenre(arg0: SongGenre): Promise<Array<SongMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByGenre(to_candid_SongGenre_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByGenre(to_candid_SongGenre_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsByReleaseType(arg0: ReleaseType): Promise<Array<SongMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsByReleaseType(to_candid_ReleaseType_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsByReleaseType(to_candid_ReleaseType_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSongsLikedByUser(): Promise<Array<SongId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSongsLikedByUser();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSongsLikedByUser();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasUserLikedSong(arg0: SongId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasUserLikedSong(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasUserLikedSong(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchSongs(arg0: string): Promise<Array<SongMetadata>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchSongs(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchSongs(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleSongLike(arg0: SongId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleSongLike(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleSongLike(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string | null, arg2: ExternalBlob | null, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async uploadSong(arg0: SongTitle, arg1: ArtistName, arg2: SongGenre, arg3: ReleaseType, arg4: SongId, arg5: ExternalBlob, arg6: ExternalBlob | null, arg7: string | null, arg8: string | null, arg9: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadSong(arg0, arg1, to_candid_SongGenre_n26(this._uploadFile, this._downloadFile, arg2), to_candid_ReleaseType_n28(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_ExternalBlob_n32(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg8), arg9 === null ? [] : [arg9]);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadSong(arg0, arg1, to_candid_SongGenre_n26(this._uploadFile, this._downloadFile, arg2), to_candid_ReleaseType_n28(this._uploadFile, this._downloadFile, arg3), arg4, await to_candid_ExternalBlob_n32(this._uploadFile, this._downloadFile, arg5), await to_candid_opt_n34(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg7), to_candid_opt_n33(this._uploadFile, this._downloadFile, arg8), arg9 === null ? [] : [arg9]);
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_ReleaseType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReleaseType): ReleaseType {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_SongGenre_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SongGenre): SongGenre {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
async function from_candid_SongMetadata_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SongMetadata): Promise<SongMetadata> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n20(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SongMetadata]): Promise<SongMetadata | null> {
    return value.length === 0 ? null : await from_candid_SongMetadata_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: _SongTitle;
    likeCount: bigint;
    songId: _SongId;
    coverBlobId: [] | [_ExternalBlob];
    genre: _SongGenre;
    blobId: _ExternalBlob;
    uploader: Principal;
    artist: _ArtistName;
    releaseType: _ReleaseType;
    uploadedAt: _Time;
    producer: [] | [string];
    featuring: [] | [string];
    year: [] | [bigint];
}): Promise<{
    title: SongTitle;
    likeCount: bigint;
    songId: SongId;
    coverBlobId?: ExternalBlob;
    genre: SongGenre;
    blobId: ExternalBlob;
    uploader: Principal;
    artist: ArtistName;
    releaseType: ReleaseType;
    uploadedAt: Time;
    producer?: string;
    featuring?: string;
    year?: bigint;
}> {
    return {
        title: value.title,
        likeCount: value.likeCount,
        songId: value.songId,
        coverBlobId: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.coverBlobId)),
        genre: from_candid_SongGenre_n15(_uploadFile, _downloadFile, value.genre),
        blobId: await from_candid_ExternalBlob_n14(_uploadFile, _downloadFile, value.blobId),
        uploader: value.uploader,
        artist: value.artist,
        releaseType: from_candid_ReleaseType_n17(_uploadFile, _downloadFile, value.releaseType),
        uploadedAt: value.uploadedAt,
        producer: record_opt_to_undefined(value.producer.length === 0 ? null : value.producer[0]),
        featuring: record_opt_to_undefined(value.featuring.length === 0 ? null : value.featuring[0]),
        year: record_opt_to_undefined(value.year.length === 0 ? null : value.year[0])
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    displayName: string;
    socialLinks: [] | [string];
    coverBlobId: [] | [_ExternalBlob];
}): Promise<{
    bio?: string;
    displayName: string;
    socialLinks?: string;
    coverBlobId?: ExternalBlob;
}> {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.bio)),
        displayName: value.displayName,
        socialLinks: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.socialLinks)),
        coverBlobId: record_opt_to_undefined(await from_candid_opt_n13(_uploadFile, _downloadFile, value.coverBlobId))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rap: null;
} | {
    other: null;
} | {
    gospel: null;
} | {
    kuduro: null;
}): SongGenre {
    return "rap" in value ? SongGenre.rap : "other" in value ? SongGenre.other : "gospel" in value ? SongGenre.gospel : "kuduro" in value ? SongGenre.kuduro : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ep: null;
} | {
    album: null;
} | {
    single: null;
}): ReleaseType {
    return "ep" in value ? ReleaseType.ep : "album" in value ? ReleaseType.album : "single" in value ? ReleaseType.single : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SongMetadata>): Promise<Array<SongMetadata>> {
    return await Promise.all(value.map(async (x)=>await from_candid_SongMetadata_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_ReleaseType_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseType): _ReleaseType {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_SongGenre_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongGenre): _SongGenre {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    displayName: string;
    socialLinks?: string;
    coverBlobId?: ExternalBlob;
}): Promise<{
    bio: [] | [string];
    displayName: string;
    socialLinks: [] | [string];
    coverBlobId: [] | [_ExternalBlob];
}> {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        displayName: value.displayName,
        socialLinks: value.socialLinks ? candid_some(value.socialLinks) : candid_none(),
        coverBlobId: value.coverBlobId ? candid_some(await to_candid_ExternalBlob_n32(_uploadFile, _downloadFile, value.coverBlobId)) : candid_none()
    };
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SongGenre): {
    rap: null;
} | {
    other: null;
} | {
    gospel: null;
} | {
    kuduro: null;
} {
    return value == SongGenre.rap ? {
        rap: null
    } : value == SongGenre.other ? {
        other: null
    } : value == SongGenre.gospel ? {
        gospel: null
    } : value == SongGenre.kuduro ? {
        kuduro: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReleaseType): {
    ep: null;
} | {
    album: null;
} | {
    single: null;
} {
    return value == ReleaseType.ep ? {
        ep: null
    } : value == ReleaseType.album ? {
        album: null
    } : value == ReleaseType.single ? {
        single: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
